# Generated by Django 5.2.3 on 2025-06-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_brand_product_rating_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
